#!/usr/bin/with-contenv sh
set -e

if ! [ -e index.php]; then
  echo >&2 "Piwik not found in $(pwd) - copying now..."
  if [ "$(ls -A)" ]; then
    echo >&2 "WARNING: $(pwd) is not empty - press Ctrl+C now if this is an error!"
    ( set -x; ls -A; sleep 10 )
  fi
  tar cf - -C /usr/src/piwik . | tar xf -
  echo >&2 "Complete! Piwik has been successfully copied to $(pwd)"
fi
